// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Hero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto px-4 py-16\"><div class=\"flex flex-wrap -mx-4\"><div class=\"w-full md:w-1/2 px-4\"><h1 class=\"text-4xl md:text-5xl font-bold text-rich-black mb-4\">unotone</h1><p class=\"text-lg text-rich-black mb-6\">unotone is a <span class=\"bg-rich-black text-dune bg-clip-border\">halftone</span> technique applied to <span class=\"bg-rich-black text-dune bg-clip-border\">duotone</span> style images</p><div class=\"flex space-x-4\"><a href=\"...\" class=\"button bg-dune text-black border-rich-black border-2 font-semibold py-2 px-4 hover:scale-105 hover:shadow-rich-black\">enhance images</a> <a href=\"...\" class=\"button bg-rich-black text-dune border-rich-black border-2 font-semibold py-2 px-4 hover:scale-105 hover:shadow-rich-black\">support author</a></div></div><div class=\"w-full md:w-1/2 px-4 flex item-center justify-center\"><div class=\"text-center\"><p class=\"text-6xl md:text-8xl font-bold counter\" hx-get=\"/api/stats/count/images\" hx-trigger=\"load\">0</p><p class=\"text-lg text-rich-black\">images processed</p></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
